# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160228_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('tweets_min', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 3, 1, 19, 0, 15, 134217, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Cpuandmemeory',
        ),
        migrations.DeleteModel(
            name='Twittercounts',
        ),
    ]
